name: Personal Website
description: >
    A simple jekyll theme aimed at programmers who like clean interface to write posts
    and show off some code.
about: >

master_repo: false
url: "http://sughosh360.github.io/"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           Sughosh V Kaushik
  avatar:         ""
  email:          "sughosh.kaushik360@gmail.com"
  # Social networking links used in footer. Update and remove as you like.
  twitter: https://twitter.com/kaushik360
  github: https://github.com/sughosh360
  stackexchange: https://stackoverflow.com/users/3833641/getsuga
  linkedin: https://www.linkedin.com/in/sughosh-kaushik-3a696099/
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
